package ecomodcompat.core;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import ecomodcompat.common.CoProxy;
import ecomodcompat.stuff.CConfig;
import net.minecraft.client.Minecraft;
import net.minecraft.crash.CrashReport;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLServerStoppingEvent;
import net.minecraftforge.fml.common.event.FMLInterModComms.IMCEvent;

@Mod(modid = CConsts.modid, name = CConsts.name, version = CConsts.version, dependencies = CConsts.deps, updateJSON = CConsts.json)

public class EcomodCompat
{
	@Instance(CConsts.modid)
	public static EcomodCompat instance;
	
	public static Logger log;
	
	@SidedProxy(modId = CConsts.modid, clientSide = CConsts.client_proxy, serverSide = CConsts.common_proxy)
	public static CoProxy proxy;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		log = LogManager.getLogger(CConsts.name);
		
		log.info("Preinitialization");
		
		if(!CConsts.asm_transformer_inited)
		{
			log.fatal("The mod ASM transformer had not been initialized!!! Unable to continue.");
			throw new NullPointerException("Ecomod ASM transformer had not been initialized!!!");
		}
		
		Configuration cfg = new Configuration(event.getSuggestedConfigurationFile());

		CConfig.config = cfg;
		
		CConfig.sync();
		
		setupMeta(event.getModMetadata());
		
		if(proxy == null)
		{
			log.fatal("Unable to load proxies!!");
			Minecraft.getMinecraft().crashed(CrashReport.makeCrashReport(new NullPointerException("Unable to load either common or client proxy!!!"), "Unable to load either common or client proxy!!!"));
			return;
		}
		
		proxy.preInit();
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event)
	{
		log.info("Initialization");
		
		proxy.init();
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event)
	{
		log.info("Postinitialization");
		
		proxy.postInit();
	}
	
	@EventHandler
	public void onIMC(IMCEvent event)
	{	
		
	}
	
	@EventHandler
	public void onServerStart(FMLServerStartingEvent event)
	{
		
	}
	
	@EventHandler
	public void onServerStopping(FMLServerStoppingEvent event)
	{
		
	}
	
	private static void setupMeta(ModMetadata meta)
	{
		meta.autogenerated=false;
		meta.credits = CConsts.contributors;
		meta.authorList = CConsts.authors;
		meta.modId = CConsts.modid;
		meta.name = CConsts.name;
		//TODO meta.logoFile =
		meta.updateJSON = CConsts.json;
		meta.url = CConsts.projectURL;
		meta.version = CConsts.version;
		
		meta.description = "An addon to MinecraftEcologyMod, which enhances its integration with other Minecraft mods.";
	}
}
