package ecomodcompat.core;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.*;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.*;
import net.minecraftforge.fml.common.versioning.DefaultArtifactVersion;

@Mod(modid = EMCConsts.MODID, name = EMCConsts.NAME,version = EMCConsts.VESRION, dependencies="required-after:"+EMCConsts.ECOMOD_ID+";")
public class EcomodCompat
{
	@Instance(EMCConsts.MODID)
	public static EcomodCompat instance;
	
	public static Logger log = null;
	
	@EventHandler
	public static void onPreInit(FMLPreInitializationEvent event)
	{
		log = LogManager.getLogger(EMCConsts.NAME);
		log.info("Preinitialization");
		setupMetadata(event.getModMetadata());
		
		if(!Loader.isModLoaded(EMCConsts.ECOMOD_ID))
		{
			log.fatal("EcologyMod had not been loaded! Unable to work!!! Please, install it from "+EMCConsts.ECOMOD_URL);
			throw new NullPointerException("EcologyMod had not been loaded! Unable to work!!! Please, install it from "+EMCConsts.ECOMOD_URL);
		}
		else
		{
			log.info("EcologyMod detected!!!");
		}
		
		EMCConfig.init();
		EMCConfig.configurate(event.getSuggestedConfigurationFile());
	}
	
	private static void setupMetadata(ModMetadata meta)
	{
		meta.autogenerated = false;
		meta.authorList = Arrays.asList(new String[]{"Artem226"});
		meta.credits = "Artem226";
		meta.dependencies = Arrays.asList(EMCConsts.ECOMOD_AS_ARTIFACT);
		meta.modId = EMCConsts.MODID;
		meta.name = EMCConsts.NAME;
		meta.description = "An addon to EcologyMod, which enhances its interaction with other mods.";
		meta.parent = EMCConsts.ECOMOD_ID;
		meta.requiredMods = EMCUtils.putToSet(new HashSet(), EMCConsts.ECOMOD_AS_ARTIFACT);
	}
	
	@EventHandler
	public static void onInit(FMLInitializationEvent event)
	{
		FMLInterModComms.sendFunctionMessage(EMCConsts.ECOMOD_ID, "add_te_pollution_determinant", EMCTEPollutionFunc.class.getName());
	}
	
	@EventHandler
	public static void onPostInit(FMLPostInitializationEvent event)
	{
		
	}
}
